---
- name: Load the OS specific variables
  tags: mysql
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the mysql packages in Redhat derivates
  tags: mysql
  yum: name={{ item }} state=present
  with_items: "{{ mysql_pkgs }}"
  when: ansible_os_family == 'RedHat'

- name: Install the mysql packages in Debian derivates
  tags: mysql
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=600
  with_items: "{{ mysql_pkgs }}"
  environment: 
    # prevent mysql from autostart after installation
    RUNLEVEL: 1
  when: ansible_os_family == 'Debian'

- name: Get mysql version
  tags: mysql
  always_run: true
  changed_when: false
  shell: mysql -V | sed -e "s/mysql  Ver [.0-9]* Distrib \([0-9]\)\.\([0-9]\)\.\([0-9]\{1,3\}\).*/\1\2/g"
  register: mysql_version

- name: Load mysql config file
  tags: mysql
  template: src=my.cnf.{{ ansible_os_family }}.j2 dest={{ mysql_conf_dir }}/my.cnf owner=root group=root mode=0644 backup=yes
  notify: 
    - restart mysql

- name: Start the mysql service
  tags: mysql
  service: name={{ mysql_service }} state=started enabled=yes

